
name: Adhoc Benchmarks (Auto-provisioned Server)

on:
  workflow_dispatch:
    inputs:
      message:
        message: 'Message'
        required: true
        default: ''
        type: string

jobs:
  hello-world:
    runs-on: ubuntu-22.04      
    steps:
    - name: Print Message
      run: echo "Hello ${{ inputs.message }}"

