# Run benchmarks on a remote system according to the release defined 
# in resources/release-benchmark-docker-compose.yml
# - Calls the reusable worflow remote-benchmarks.yml

name: Release Benchmark Test on Docker Deephaven

on:
  workflow_dispatch:
    branches: [ "**" ]

jobs:
  process-release-benchmarks:
    uses: ./.github/workflows/remote-benchmarks.yml
    with:
      run_type: release
    secrets: inherit
