# Run benchmarks on a remote system according to the release defined 
# in resources/release-benchmark-docker-compose.yml
# - Calls the reusable worflow remote-benchmarks.yml

name: Release Benchmark Test on Docker Deephaven

on:
  workflow_dispatch:
    inputs:
     docker_image:
       description: 'Docker Image Name'
       required: true
       default: '0.32.0'
       type: string

jobs:
  process-release-benchmarks:
    uses: ./.github/workflows/remote-benchmarks.yml
    with:
      run_type: release
      docker_image: ${{ inputs.docker_image }}
      run_label: ""
      test_package: "io.deephaven.benchmark.tests.standard"
      test_class_regex: "^(Test.*|.+[.$]Test.*|.*Tests?)$"
      scale_row_count: 10000000
      distribution: random
    secrets: inherit
