# Run benchmarks on a remote system for the release the project is using
# - This workflow is reusable with run-type set to release or nightly
# - Scripts ending in "-local" run on the github runner
# - Scripts ending in "-remote" run are executed on the remote test server through ssh

name: Benchmark Test on Docker Deephaven

on:
  workflow_call:
    inputs:
      run-type:
        required: true
        type: string

jobs:
  process-benchmarks:

    runs-on: ubuntu-22.04
    env:
      SD: .github/scripts
      HOST: ${{secrets.BENCHMARK_HOST}}
      USER: ${{secrets.BENCHMARK_USER}}
      REPO: ${{github.repository}}
      BRANCH: ${{github.ref_name}}
      RUN_TYPE: ${{inputs.run-type}}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Local and Remote Scripts
      run: |
        sudo chmod +x ${SD}/*
        ${SD}/setup-ssh-local.sh ${HOST} "${{secrets.BENCHMARK_KEY}}"

    - name: Run Remote Test Server Setup
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} setup-test-server-remote ${REPO} ${BRANCH} ${RUN_TYPE}

    - name: Run Remote Benchmark Artifact Build
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} build-benchmark-artifact-remote

    - name: Run Remote Benchmarks
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} run-benchmarks-remote ${RUN_TYPE}
        
    - name: Fetch Benchmark Results
      run: |
        ${SD}/fetch-results-local.sh ${HOST} ${USER} ${RUN_TYPE}
        
    - name: Manage Summary Results
      run: |
        # For now remove any unwanted summaries before uploading to GCloud
        rm -f ${RUN_TYPE}/*.csv
        # Rename the svg summary table according to run type. Discard the rest
        TMP_SVG_DIR=${RUN_TYPE}/tmp-svg
        mkdir -p ${TMP_SVG_DIR}
        mv ${RUN_TYPE}/*.svg ${TMP_SVG_DIR}
        mv ${TMP_SVG_DIR}/${RUN_TYPE}-benchmark-summary.svg ${RUN_TYPE}/benchmark-summary.svg
        rm -rf ${TMP_SVG_DIR}

    - name: Authorize GCloud Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{secrets.BENCHMARK_GCLOUD}}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Backup Existing Benchmark Summary SVG
      run: |
        SUMMARY_PREFIX=gs://deephaven-benchmark/${RUN_TYPE}/benchmark-summary
        if gsutil stat ${SUMMARY_PREFIX}.svg &>/dev/null; then
          gsutil mv ${SUMMARY_PREFIX}.svg ${SUMMARY_PREFIX}.prev.svg &>/dev/null
        fi

    - name: Upload Benchmark Results to GCloud
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ${{env.RUN_TYPE}}
        destination: deephaven-benchmark
   
    - name: Pulish Slack Notification Tables
      run: |
        run-publish-local.sh ${RUN_TYPE} "${{secrets.SLACK_CHANNEL}}" "${{secrets.SLACK_URL}}" 

    - name: Archive Results
      uses: actions/upload-artifact@v3
      with:
        name: Benchmarks and Logs
        path: |
          ${{env.RUN_TYPE}}/**/*
          logs/**/*


