# Run benchmarks on a remote system and produces benchmark results and logs locally
# - Scripts ending in "-local" run in the workflow at github
# - Scripts ending in "-remote" run are executed on the remote test server through ssh

name: Benchmark Test on Docker Deephaven

on:
  push:
    branches: [ "**" ]
  schedule:
    # 3AM EST == 7 UTC
    - cron: '0 7 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04
    env:
      SD: .github/scripts

    steps:
    - uses: actions/checkout@v3
    - name: Setup Local and Remote Scripts
      run: |
        sudo chmod +x ${SD}/*
        ${SD}/setup-ssh-local.sh ${{secrets.BENCHMARK_HOST}} "${{secrets.BENCHMARK_KEY}}"

    - name: Run Remote Test Server Setup
      run: |
        ${SD}/run-ssh-local.sh ${{secrets.BENCHMARK_HOST}} ${{secrets.BENCHMARK_USER}} ${SD} setup-test-server-remote

    - name: Run Remote Benchmark Artifact Build
      run: |
        ${SD}/run-ssh-local.sh ${{secrets.BENCHMARK_HOST}} ${{secrets.BENCHMARK_USER}} ${SD} build-benchmark-artifact-remote

    - name: Run Remote Benchmarks
      run: |
        ${SD}/run-ssh-local.sh ${{secrets.BENCHMARK_HOST}} ${{secrets.BENCHMARK_USER}} ${SD} run-benchmarks-remote
        
    - name: Fetch Benchmark Results
      run: |
        ${SD}/fetch-results-local.sh ${{secrets.BENCHMARK_HOST}} ${{secrets.BENCHMARK_USER}}
        
    - name: Authorize GCloud Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.BENCHMARK_GCLOUD }}
        
    - name: Upload Benchmark Results to GCloud
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: results
        destination: deephaven-benchmark

    - name: Archive Results
      uses: actions/upload-artifact@v3
      with:
        name: Benchmarks and Logs
        path: |
          results/**/*
          logs/**/*
