# Run benchmarks on a remote system and produces benchmark results and logs locally
# - Scripts ending in "-local" run in the workflow at github
# - Scripts ending in "-remote" run are executed on the remote test server through ssh

name: Benchmark Test on Docker Deephaven

on:
  push:
    branches: [ "**" ]
  schedule:
    # 3AM EST == 7 UTC
    - cron: '0 7 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04
    env:
      SD: .github/scripts
      HOST: ${{secrets.BENCHMARK_HOST}}
      USER: ${{secrets.BENCHMARK_USER}}
      REPO: ${{github.repository}}
      BRANCH: ${{github.ref_name}}
      RUN_TYPE: release

    steps:
    - uses: actions/checkout@v3
    - name: Setup Local and Remote Scripts
      run: |
        sudo chmod +x ${SD}/*
        ${SD}/setup-ssh-local.sh ${HOST} "${{secrets.BENCHMARK_KEY}}"

    - name: Run Remote Test Server Setup
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} setup-test-server-remote ${REPO} ${BRANCH} ${RUN_TYPE}

    - name: Run Remote Benchmark Artifact Build
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} build-benchmark-artifact-remote

    - name: Run Remote Benchmarks
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} run-benchmarks-remote
        
    - name: Fetch Benchmark Results
      run: |
        ${SD}/fetch-results-local.sh ${HOST} ${USER} ${RUN_TYPE}
        
    - name: Remove Summary Results
      run: |
        # For now remove any summaries before putting in GCloud
        rm -f results/*.csv
        
#    - name: Authorize GCloud Credentials
#      uses: google-github-actions/auth@v1
#      with:
#        credentials_json: ${{secrets.BENCHMARK_GCLOUD}}
        
#    - name: Upload Benchmark Results to GCloud
#      uses: google-github-actions/upload-cloud-storage@v1
#      with:
#        path: ${RUN_TYPE}/
#        destination: deephaven-benchmark

    - name: Archive Results
      uses: actions/upload-artifact@v3
      with:
        name: Benchmarks and Logs
        path: |
          ${{env.RUN_TYPE}}/**/*
          logs/**/*
