# Run benchmarks on a remote system for the release the project is using
# - This workflow is reusable with run_type set to release or nightly
# - Scripts ending in "-local" run on the github runner
# - Scripts ending in "-remote" run are executed on the remote test server through ssh

name: Benchmark Test on Docker Deephaven

on:
  workflow_call:
    inputs:
      run_type:
        required: true
        type: string
      docker_image:
       required: true
       type: string
      run_label:
        required: true
        type: string
      test_package:
        required: true
        type: string
      test_class_regex:
        required: true
        type: string
      test_iterations:
        required: true
        type: string
      scale_row_count:
        required: true
        type: string
      distribution:
        required: true
        type: string

jobs:
  process-benchmarks:

    runs-on: ubuntu-22.04
    env:
      SD: .github/scripts
      HOST: ${{secrets.BENCHMARK_HOST}}
      USER: ${{secrets.BENCHMARK_USER}}
      REPO: ${{github.repository}}
      BRANCH: ${{github.ref_name}}
      RUN_TYPE: ${{inputs.run_type}}
      DOCKER_IMG: ${{inputs.docker_image}}
      RUN_LABEL: ${{inputs.run_label}}
      TEST_PKG: ${{inputs.test_package}}
      TEST_RGX: ${{inputs.test_class_regex}}
      ROW_CNT: ${{inputs.scale_row_count}}
      DISTRIB: ${{inputs.distribution}}
      TEST_ITERS: ${{inputs.test_iterations}}
      ACTOR: ${{github.actor}}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Local Scripts
      run: |
        sudo chmod +x ${SD}/*
        ${SD}/setup-ssh-local.sh ${HOST} "${{secrets.BENCHMARK_KEY}}"

    - name: Run Remote Test Server Setup
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} setup-test-server-remote ${REPO} ${BRANCH} ${RUN_TYPE} "${DOCKER_IMG}"

    - name: Run Remote Server Distribution Build
      if: ${{ contains(env.DOCKER_IMG, '::') }}
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} build-server-distribution-remote "${DOCKER_IMG}"
        
    - name: Run Remote Docker Image Build
      if: ${{ contains(env.DOCKER_IMG, '::') }}
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} build-docker-image-remote

    - name: Start Remote Remote Deephaven Server
      run: | 
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} manage-deephaven-remote start "${DOCKER_IMG}"

    - name: Run Remote Benchmark Artifact Build
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} build-benchmark-artifact-remote

    - name: Run Remote Benchmarks
      run: |
        ${SD}/run-ssh-local.sh ${HOST} ${USER} ${SD} run-benchmarks-remote ${RUN_TYPE} "${TEST_PKG}" "${TEST_RGX}" ${ROW_CNT} ${DISTRIB} ${TEST_ITERS}
        
    - name: Fetch Benchmark Results and Prepare for Upload
      run: |
        ${SD}/fetch-results-local.sh ${HOST} ${USER} ${SD} ${RUN_TYPE} "${ACTOR}" "${RUN_LABEL}" "${DOCKER_IMG}"

    - name: Authorize GCloud Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{secrets.BENCHMARK_GCLOUD}}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Backup Existing Benchmark Summary SVG
      run: |
        SUMMARY_PREFIX=gs://deephaven-benchmark/${RUN_TYPE}/benchmark-summary
        if gsutil stat ${SUMMARY_PREFIX}.svg &>/dev/null; then
          gsutil mv ${SUMMARY_PREFIX}.svg ${SUMMARY_PREFIX}.prev.svg &>/dev/null
        fi

    - name: Upload Benchmark Results to GCloud
      uses: google-github-actions/upload-cloud-storage@v1
      with:
        path: ${{env.RUN_TYPE}}
        destination: deephaven-benchmark
        
    - name: Sync GCloud with Demo NFS
      run: |
        gcloud compute ssh --zone "us-central1-a" --project "deephaven-oss" dhc-demo-nfs-client --command="sudo gsutil -m rsync -d -r gs://deephaven-benchmark /nfs/deephaven-benchmark"
        gcloud compute ssh --zone "us-central1-a" --project "deephaven-oss" dhc-demo-nfs-client --command="sudo find /nfs/deephaven-benchmark -mindepth 1 -type d -empty -delete"
        
    - name: Publish Slack Notification Tables
      run: |
        ${SD}/run-publish-local.sh ${RUN_TYPE} "${{secrets.BENCHMARK_SLACK_CHANNEL}}" "${{secrets.BENCHMARK_SLACK_TOKEN}}" 

    - name: Archive Results
      uses: actions/upload-artifact@v3
      with:
        name: Benchmarks and Logs
        path: |
          ${{env.RUN_TYPE}}/**/*
          logs/**/*


