name: Benchmark Test on Docker Deephaven

on:
  push:
    branches: [ "**" ]
  schedule:
    # 3AM EST == 7 UTC
    - cron:  '0 7 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup and Run Benchmarks
      run: |
        SD=.github/scripts
        sudo chmod +x ${SD}/*
        ${SD}/setup-run-benchmark-local.sh ${{secrets.BENCHMARK_HOST}} ${{secrets.BENCHMARK_USER}} "${{secrets.BENCHMARK_KEY}}" ${SD}
    - name: Archive Results
      uses: actions/upload-artifact@v3
      with:
        name: Integration Benchmarks and Logs
        path: |
          test-server-setup.log
